### PR TITLE
removing deprecated methods and simplifying code

### PR DESCRIPTION
**Pull request by amatosg**
- `ProfileManager.getActiveProfile() `has been deprecated in favor of `ConfigUtils.getProfiles()`
- Code improvement

### CODE REVIEW

**Comment by mraible** [comment]
@amatosg Can you please merge the `main` branch with yours to see if more CI tests pass?

**Comment by mraible** [comment]
@amatosg I was able to merge the `main` branch. Now tests are failing. Please review when you get a chance.

**Comment by amatosg** [comment]
I'm on holidays ATM. Will do as soon as I get back

**Comment by mraible** [comment]
@amatosg Are you still working on this?

**Comment by mraible** [comment]
Closing this PR since tests are failing. Please reopen if you'd still like to see improvement.

**Pull request closed without merging**
