### PR TITLE
Added new keycloak realm config jsons for quarkus authorization bug

### PR DESCRIPTION
**Pull request by dminkovski**
hey @danielpetisme !
Here are the json files in the original generator-jhipster directory structure.
Please let me know if I misunderstood something or if I need to change the structure.

Glad to help and thank you for your amazing work! 👍 

Best regards

### CODE REVIEW

**Comment by danielpetisme** [comment]
Hi David,
Sorry I misunderstood the fix.

The Keycloak json are inherited from 
https://github.com/jhipster/generator-jhipster/tree/main/generators/docker-compose/templates/realm-config

JHipster Quarkus is not maintaining them, the PR should be made to the upstream repo.

**Comment by dminkovski** [comment]
Hi Daniel,

no worries thanks!
I just thought, since this seems to be a quarkus-only related issue - we could use it here.
I will do a PR in the upstream repo then. 
Any help much appreciated!

Thanks

**Comment by danielpetisme** [comment]
Are you sure it can only be solved by a realm update ?
I mean, if the json work fine with the upstream jhipster, maybe it's the Quarkus Java code with does no do the job.

Have a look at 
https://github.com/jhipster/generator-jhipster-quarkus/blob/main/generators/server/templates/quarkus/src/main/java/package/web/rest/AccountResource.java.ejs#L131

And 
https://github.com/jhipster/generator-jhipster-quarkus/blob/main/generators/server/templates/quarkus/src/main/resources/application.properties.ejs#L88

Maybe we're missing something here, but if  the realms work with Jhipster Spring it must be only a configuration issue on the application,

What do you think?

**Comment by dminkovski** [comment]
Hey daniel I think you are right!

I am going to make a new PR 👍

**Comment by dminkovski** [comment]
Hi @danielpetisme,

would you be so kind as to guide me through this PR?
I have added the fix in the application.properties file.
Your help is much appreciated!

**Comment by danielpetisme** [comment]
Hi!

You actually did the right thing!

I re-triggered the tests because one was failing (most of the time it's a Maven downloading issue and not code related).
If the tests are green, that would mean we're in a very good direction.

I do have a question, As far as I know `microprofile-jwt` is not a standard claim. I think I had an issue when integrated with Okta. I can test that, if there is a mismatch between the 2 Oauth2 provides we would have to add a condition in the `application.properties` template.

I am wondering if we could add some tests?
There 2 main types of tests:
- Testing the generator. The idea would be to check the content of `application.properties` to ensure the proper scopes are present
https://github.com/jhipster/generator-jhipster-quarkus/blob/main/test/server.spec.js#L291
- Testing the java code. Generating a Java code that ensures the Keycloak JWT contains the scope
Do you think you can complete the tests.

**Comment by dminkovski** [comment]
@danielpetisme 
Hey thanks so much for the help!
I will look into it, might need some time though.

Will write up the tests and make the configuration in the properties template.
I will hit you up once I am done or need any help.

Thanks so much!

**Comment by dminkovski** [comment]
Hey @danielpetisme 

So I thought about this and I think it makes sense to differentiate between keycloak and okta anyways in the long run of things.
In order to add a condition in the application.properties template, we would have to add a question in the generator after the oauth2 e.g "Which ${chalk.yellow('*authenticationType*')} would you like to use?" "Keycloak", "Okta", "Other".

I would then write up the conditional logic for the properties and the tests.

What are your thoughts on that?

Thanks and best regards

**Comment by dminkovski** [comment]
@danielpetisme 
Hey I committed the code I thought could work, let me know if I missed something or if I am off to a completely wrong direction.
Also regarding the Java tests. I would be more than happy to write them up, but since I would probably be using wiremock and jose4j or smth. to generate the token with the right claims myself, I am not sure its entirely valuable...what do you think?

**Comment by danielpetisme** [comment]
🤔 
I would like to avoid that as much as if possible... 
Upstream Jhipster and other blueprints (.Net, Node.JS) manage to solve the issue with adding a question, I think it would be nice to keep it consistent.

Basically we need the `roles` claim no? Is it a claim that both Keycloak and Okta implement? 

WDYT?

**Comment by dminkovski** [comment]
@danielpetisme I implemented a question if you look into the commit, but I will check out the other blueprints too.
Maybe I can find some "best practice".
We actually need the microprofile-jwt claim...I added the roles just in case someone needs more. But I can get rid of it.
I have not used Okta yet - so I do not know the requirements there.

Let me know in which direction we should head?

**Comment by danielpetisme** [comment]
Hi @dminkovski I'm struggling to have a proper look at what you proposed.
I'll do my best to give you a quick answer.

**Comment by dminkovski** [comment]
Hey @danielpetisme any news on your side? Please let me know if I can help in speeding up the process.
Best regards!

**Comment by danielpetisme** [comment]
Hi!
I feel sorry to say I didn't spend any time on this PR... #shame

In a Quarkus context, Oauth2 works nice with Angular so I don't understand why it would be any different with React.

For me it can't be a keycloak configuration issue since we inherit JHipster-Spring Keycloak configuration without touching it. As far as I know, both frontends works properly with JHipster Spring so I guess there is an issue in the `/account` response, or a bad oauth2 client configuration.

I would like to have both frontends and compare the way they are consumer JHipster responses.

Can you create a repo github in which you create 2 JHipster Quarkus projects. One for angular and one for react.
Thank you

**Comment by dminkovski** [comment]
Hey no worries and thanks for your time!

Actually I think this is a misunderstanding. 
I was thinking of using the quarkus blueprint for a gateway application - I found out that it can only be used as a microservice (correct me if I am wrong). Because I was also having trouble with the routing (gateway) and keycloak authentication.
The implementation of the UserOauth2Controller - OAuth2 Flow is just different.
It has nothing to do with Angular vs. React imo.

That is why I suggested to add a different configuration for it to work with quarkus as the gateway instead of springboot default. But it would also mean to implement other features of a gateway. 

Thus the quarkus blueprint can only be used for the microservice for now, correct? 
BTW I have implemented Elastic Search successfully as well and might look into a PR once I am confident with it.

Sorry for the inconvenience or if am misunderstanding something...
Best

**Comment by danielpetisme** [comment]
Hi @dminkovski 
You're right.
As for now, the Quarkus blueprint does not provide the JHipster microservice pattern.
This is a choice I made on purpose. I'm not sure there is an interest to introduce this kind of complexity and I tend to prefer to delegate microservice concerns to an infrastructure layer.
This is a discussion I have often :) So I guess at some point, I'll have to reconsider it.

Anyway, from what I understand you were trying to mix a JHipster (Spring) gateway and a JHipster Quarkus application.
Am I correct?
I would be very curious if you have a sample repo I could look at.


Are you ok to close both the issue and PR?

Note: That's would be awesome to have a support of ElasticSearch!! Feel free to open a PR to discuss about it.

**Comment by dminkovski** [comment]
@danielpetisme Okay will do once I got ES integrated into the generator I will open a PR! Thanks for your support :)

**Pull request closed without merging**
