### PR TITLE
Customize JHipster 7 features.

### PR DESCRIPTION
**Pull request by mshima**
- Change user api endpoint from /api/users to /api/admin/users.
- Rename jdl samples from .jh to .jdl
- Reformat workflows to tabWith 2 to match jhipster main repository format.
- Add cypress to samples, disable failing tests.
- Customize package.json scripts.

related to https://github.com/jhipster/generator-jhipster-quarkus/pull/223

### CODE REVIEW

**Comment by avdev4j** [comment]
not sure to understand why we need to change the users endpoint. 
I plan to do a new beta release including JHipster 7, I guess this one should be included.

**Comment by mshima** [comment]
Or customize endpoints at clients:
https://github.com/jhipster/generator-jhipster/blob/aa9f3475582d7e4e751eb8ee1f7775762ccc2ebc/generators/client/templates/angular/src/main/webapp/app/admin/user-management/service/user-management.service.ts.ejs#L33

**Comment by mshima** [comment]
@avdev4j do you prefer to change the client endpoint instead?

**Comment by avdev4j** [comment]
as I understand we changed the endpoints generated by JHipster and now we have 2 solutions:
- changing the Quarkus code to expose the same endpoints
- changing the frontend to reach the old one

If this is it, I'd rather like to change the endpoint in the backend. JHipster Quarkus is a "backend" blueprint, if we can avoid changing the frontend, it's better.

**Comment by mshima** [comment]
> as I understand we changed the endpoints generated by JHipster

Yes.

> If this is it, I'd rather like to change the endpoint in the backend. JHipster Quarkus is a "backend" blueprint, if we can avoid changing the frontend, it's better.

That’s it.

**Comment by avdev4j** [comment]
Great! So let's merge this one, if it's ready.

**Comment by mshima** [comment]
I don’t have commit rights.

**Pull request merged**
