### PR TITLE
Address the issue #179 - fix building native image with the MongoDB

### PR DESCRIPTION
**Pull request by vektory79**

### CODE REVIEW

**Comment by vektory79** [comment]
Seems like more investigation needed to find the way to adding migration scripts to the reflection configs.

**Comment by vektory79** [comment]
#180 - adding support of the Mongock for native image

**Comment by vektory79** [comment]
#179 - adding support of the Mongock for native image

**Comment by avdev4j** [comment]
Hey @vektory79 
I've tested it and it sounds good. Could you please just update the generator tests (inside the test folder) when we choose Mongo. Then I will merge this PR.
https://github.com/jhipster/generator-jhipster-quarkus/blob/main/test/server.spec.js#L351

https://github.com/jhipster/generator-jhipster-quarkus/blob/main/test/utils/expected-files.js#L103

**Comment by vektory79** [comment]
Something weird happens here. I can't understand what thing breaking all of the tests. :(

**Comment by avdev4j** [comment]
yes, I've just figured out the Ci is using the last JHipster version instead of the good one. Since JHi7 has been released it makes it failed.

I will try to get a look tomorrow and fix that.

**Comment by avdev4j** [comment]
I fixed it, you can rebase @vektory79

**Comment by vektory79** [comment]
Yoohoo! It's done :)

**Comment by avdev4j** [comment]
Thanks for your contribution @vektory79 

Don't forget to claim your bounty and put the link in this PR so we can validate it.

See you soon on JHipster Quarkus!

**Comment by vektory79** [comment]
Claimed: https://opencollective.com/generator-jhipster/expenses/36933

Thanks!

**Comment by pascalgrimaud** [comment]
@vektory79 : approved

**Comment by dieppa** [comment]
I already made this comment in another ticket related to this, but I just reproduce it again:

```
I have just realised about this ticket and it seems that has been somehow sorted out.

However is there anything that we can provide natively from Mongock to help on this or improve.

Just us me know.
```

**Pull request merged**
