### PR TITLE
Upgrade to JHipster 7

### PR DESCRIPTION
**Pull request by avdev4j**
- [x] Upgrade to JHipster 7
- [x] remove UAA
- [x] remove setupXXVersion
- [x] Add new lifecycle methods
- [ ] update Vue health check https://github.com/jhipster/generator-jhipster-quarkus/issues/98
- [x] Use composing function in the app generator instead of defining the composed subgen in the configuring() method https://github.com/jhipster/generator-jhipster/blob/main/generators/app/index.js#L387
- [ ] Use composing function in the entity generator instead of defining the composed subgen in the configuring() method
- [x] Fix the todo here https://github.com/jhipster/generator-jhipster-quarkus/blob/main/generators/entity-server/index.js#L68
- [ ] The CI is green

### CODE REVIEW

**Comment by mraible** [comment]
Anything I can do to help with this? I'd like to create a screencast of [this post](https://developer.okta.com/blog/2021/03/08/jhipster-quarkus-oidc). However, I think it'd be nice to update it for Quarkus 2.0 first. Are there plans to release a new version of this blueprint with Quarkus 2.0 support in the next week or two?

**Comment by avdev4j** [comment]
Hi Matt,
I'm working on it but I'm struggling a bit with the entity subgen. I think every other things are working.

The entity subgen is quite complexe to migrate due to several changes in JHipster. If you want you can contribute on this part.

There is also the vue part to modify but it's a minor change.

We plan to release a new version (a beta has been released with Quarkus 2 and SQL DB) including JHipster and the whole support of Quarkus 2 (redis, mongo...). Not sure it will be done in one or two weeks.

**Comment by mraible** [comment]
I added a bug bounty that might help. @mshima was a big help in migrating the Ionic module to JHipster 7. https://github.com/oktadev/generator-jhipster-ionic/pull/482

**Comment by avdev4j** [comment]
As far as I know the main problem could be resolved by checking how the context is loaded inside the BP and ensure the composing part is made as expected.

**Comment by mraible** [comment]
@avdev4j Can you fix the conflicts please?

**Comment by avdev4j** [comment]
fixed @mraible

**Comment by mraible** [comment]
Any chance you can help with this upgrade, @mshima? If not, I can take a look next week.

**Comment by mshima** [comment]
I will take a look.

**Comment by mshima** [comment]
I don't have permission to push to this branch, created https://github.com/jhipster/generator-jhipster-quarkus/pull/223.

**Comment by mshima** [comment]
@avdev4j can we split in half? $250 each?

**Comment by avdev4j** [comment]
I'm sorry @mshima I totally forgot to answer you, yes let's go for it! 250 each

**Comment by avdev4j** [comment]
Claimed here https://opencollective.com/generator-jhipster/expenses/55564

**Comment by pascalgrimaud** [comment]
@avdev4j : approved
Waiting yours, @mshima

**Comment by mshima** [comment]
@pascalgrimaud half bounty claimed https://opencollective.com/generator-jhipster/expenses/59119.

**Comment by pascalgrimaud** [comment]
@mshima : approved

**Comment by mshima** [comment]
Thanks @pascalgrimaud

**Pull request closed without merging**
