### PR TITLE
Integrating Quarkus Zalando problem

### PR DESCRIPTION
**Pull request by danielpetisme**
The spring generator relies on Zalando problem library to produce machine friendly HTTP response.
This PR aims to align Quarkus to this API contract.

The PR relies on https://github.com/cloudstark/quarkus-zalando-problem-extension

### CODE REVIEW

**Comment by danielpetisme** [comment]
The main concern is the activity of the https://github.com/cloudstark/quarkus-zalando-problem-extension project

To be honest I asked to the library if they plan to still maintain it: https://github.com/cloudstark/quarkus-zalando-problem-extension/issues/91

If they don't want to maintain it what would be the options?
- Develop a Zalando problem extension under the JHipster organisation (quarkus does not want to host and maintain 3rd party extensions anymore, it's way to much work for them)?
- try to just cover the Jhipster part. IMHO, it's a dozen of exception, 401/403, constraints validations and couple of custom Jhipster exceptions.

WDYT @avdev4j @joewhite101 ?

**Comment by avdev4j** [comment]
Hi @danielpetisme
Indeed the project seems not to be maintained anymore. Do you think there is many things to do? (maintenance, improvements...).

I don't understand your second proposition but I think if we could have an extension under the JHipster organisation it will be awesome for visibility. Maybe it's a way to reach easily developers

**Comment by danielpetisme** [comment]
The second option is to embed the serialization of jhipster exceptions to the same json structure Zalando Problem proposes. This would integrate nicely to the front (it's the beauty of API).

Basically it means implementing customs `ExceptionMapper`s.

**Comment by SchulteMarkus** [comment]
> Hi @danielpetisme
> Indeed the project seems not to be maintained anymore. Do you think there is many things to do? (maintenance, improvements...).
> 
> I don't understand your second proposition but I think if we could have an extension under the JHipster organisation it will be awesome for visibility. Maybe it's a way to reach easily developers

I had been committer to https://github.com/cloudstark/quarkus-zalando-problem-extension for some time. I am pretty sure the project is dead for time being, the project owner is unreachable, see https://github.com/cloudstark/quarkus-zalando-problem-extension/issues/91
Last time I visited the project there was not much left to do releasing a beta version, in my opinion, see https://github.com/cloudstark/quarkus-zalando-problem-extension/issues . In my opinion, there is only one issue "get to extension up to date to latest Quarkus" missing.

**Comment by SchulteMarkus** [comment]
> Thanks @SchulteMarkus for your feedback!
> We're considering taking over/reset the project, who knows maybe you'll be ready to help us wink

To be honest, I am low on time. Maybe during the Christmas holidays, but I can't promise.

**Comment by danielpetisme** [comment]
I take the opportunity to thank you for what you have done!

**Comment by danielpetisme** [comment]
Since the quarkus-zalando-lib is not maintained I'm closing the issue to propose a new solution.

**Pull request closed without merging**
