### PR TITLE
7.x features

### PR DESCRIPTION
**Pull request by mshima**
Missing:
- [x] Test angular customizations.
- [x] Test react customizations.
- [x] Update endpoint api with the id.

Closes https://github.com/jhipster/generator-jhipster-quarkus/pull/185

### CODE REVIEW

**Comment by mraible** [comment]
I looked through each of the CI failures and here's a summary:

imperative-ngx-jwt-maven-mongodb-caffeine:

```
Error:  io.github.jhipster.sample.web.rest.UserResourceTest  Time elapsed: 17.815 s  <<< ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.NoSuchMethodError: 'com.mongodb.internal.connection.Cluster com.mongodb.internal.connection.DefaultClusterFactory.createCluster(com.mongodb.connection.ClusterSettings, com.mongodb.connection.ServerSettings, com.mongodb.connection.ConnectionPoolSettings, com.mongodb.connection.StreamFactory, com.mongodb.connection.StreamFactory, com.mongodb.MongoCredential, com.mongodb.event.CommandListener, java.lang.String, com.mongodb.MongoDriverInformation, java.util.List)'
```

imperative-react-jwt-gradle-mysql-caffeine: Gradle issue - maybe because of Gradle 7?

imperative-ngx-jwt-maven-mysql-redis: A few tests are failing with:

```
java.lang.RuntimeException: Can't start redis server. Check logs for details.
```

**Comment by mshima** [comment]
@mraible I'm not trying to fix any quarkus problem, but to generate identical to what the main branch generates.

I didn't realized I fixed imperative-sql-jwt-maven-noDb, but broke imperative-react-jwt-gradle-mysql-caffeine.
I will try to fix imperative-react-jwt-gradle-mysql-caffeine.

I think we should merge this without trying to fix quarkus bugs in this PR, this migration is already complicated enough.
Then we can try to add cypress.

**Comment by mraible** [comment]
@mshima Sounds good! Please let me know if I can help.

**Comment by mshima** [comment]
Reverted gradle to 6.5.
Fixed react test.

Diff between main and this branch is available here: https://github.com/mshima/generator-jhipster-quarkus/pull/2/checks?check_run_id=3352418606.

**Comment by mraible** [comment]
The latest `main` branch has `12 failing and 6 successful checks`. This PR has `8 successful and 2 failing checks` so I'm going to merge it since it's better.

**Review by mraible — APPROVED** [review]

**Comment by avdev4j** [comment]
Hi @mshima 
a few questions for you,
- the sbs blueprint is used to only replace existing files, that's it? how does the generator know which file it has to override? (the files-xxx.js has been removed)
- in the common generator, what this function means `notEmpty() {}`
- in the entity generator we don't have the same signature as the others `constructor(args, options, features)` is it intended?
- in the app index.js file, why do we need to delete applicationWithEntities `delete options.applicationWithEntities;`
- in the client generator, we use `deleteDestination()` method, where is it come from?
- same generator, you've added a note regarding a bug in JHipster 7.1.0, can you put the reference (the URL) if there is one, so we can remove the workaround when the bug will be fixed.


Thank you!

**Comment by mshima** [comment]
> * the sbs blueprint is used to only replace existing files, that's it?

It can do pretty much anything, but it doesn't change the original generator workflow.
But you can change it's behavior by changing it:
eg `this.options.jhipsterContext.skipHealth = true` (this is an concept, it's not supported by the generator)

> how does the generator know which file it has to override? (the files-xxx.js has been removed)

Precedence, sbs blueprints adds itself as a template source.
https://github.com/mshima/generator-jhipster/blob/c55fa59c86c1adeade03013117ac60b5b0c7d582/generators/generator-base.js#L2145-L2154

> * in the common generator, what this function means `notEmpty() {}`

generators much have at least 1 task.

> * in the entity generator we don't have the same signature as the others `constructor(args, options, features)` is it intended?

No, forgot, but is unlikely to cause problems.

> * in the app index.js file, why do we need to delete applicationWithEntities `delete options.applicationWithEntities;`

Workaround to custom cli options not working: `jhipster jdl foo.jdl --blueprints quarkus --client-framework react`.
client-framework will be overridden without this workaround.

> * in the client generator, we use `deleteDestination()` method, where is it come from?

https://yeoman.github.io/generator/actions_fs.html#.deleteDestination

> * same generator, you've added a note regarding a bug in JHipster 7.1.0, can you put the reference (the URL) if there is one, so we can remove the workaround when the bug will be fixed.

https://github.com/jhipster/generator-jhipster/issues/15884
It's fixed at main branch. Can be dropped for next jhipster release.

**Pull request merged**
