### PR TITLE
switch keycloak to v23 in test

### PR DESCRIPTION
**Pull request by mshima**

### CODE REVIEW

**Comment by mraible** [comment]
Closing and reopening to see if this is fixed now.

**Comment by mshima** [comment]
@mraible test is relying on password grant type:
https://github.com/jhipster/generator-jhipster-quarkus/blob/158dddd36b8024ce22dbe3c6e114d5ca09579dbb/generators/quarkus/templates/src/test/java/_package_/utility/IntegrationTestBase_oauth2.java.ejs#L48-L67

Maybe we should remove the test.

**Comment by mraible** [comment]
@mshima Yes, that test seems to be unnecessary.

**Comment by mshima** [comment]
Password grant type is probably disabled at keycloak 23 by default.
That’s probably the error.

**Comment by mraible** [comment]
> Password grant type is probably disabled at keycloak 23 by default.

That's good. It should be.

**Comment by vishal423** [comment]
password grant was added specifically to run Integration (Native) tests that don't have access to UI. In absence of authentication mechanism, I doubt the integration tests can work that require user to be logged-in. Also, do note that the password grant was enabled only in the realm used by tests (we create a copy during code generation under test directory) and not enabled in the one used by application.

**Review by mraible — APPROVED** [review]

**Pull request merged**
