### PR TITLE
Feature/mongodb

### PR DESCRIPTION
**Pull request by amanganiello90**
I have only added the mongodb client dependency with related properties. The other commits are the same of the feature/github-pipeline PR

### CODE REVIEW

**Comment by danielpetisme** [comment]
You're moving fast!! Cool
I think you need to rebase your branch.

**Comment by amanganiello90** [comment]
Yes, now it is rebased. Thanks

**Comment by danielpetisme** [comment]
Hello 


I don't know if you are waiting a review?

Do you plan to generate the entity repository + test within this PR?

**Comment by amanganiello90** [comment]
Hi! I have to update this. You can decline it and I will open another PR.

**Comment by danielpetisme** [comment]
As you wish, I don't mind to have it on this one, I don't have any reasons to close it.

**Comment by joewhite101** [comment]
hey @amanganiello90 this is still a work in progress right? Going to close this PR but feel free to open a new one if you're ready for review.

**Comment by amanganiello90** [comment]
Ok thanks

**Pull request closed without merging**
