### PR TITLE
Add authentication prompt for OAuth 2.0 / OIDC

### PR DESCRIPTION
**Pull request by mraible**
Necessary for the front-end to generate the proper code for OIDC. Helps with #47.

### CODE REVIEW

**Comment by mraible** [comment]
@joewhite101 Should I be concerned that no CI tests run on PRs?

**Comment by mraible** [comment]
Hah! As soon as I posted this, the CI tests started.

**Review by joewhite101 — APPROVED** [review]
LGTM

**Comment by avdev4j** [comment]
We have an issue with tests here : `Caused by: org.h2.jdbc.JdbcSQLException: Column "USER0_.ACTIVATION_KEY" not found; SQL statement:`

It seems that the ACTIVATION_KEY column still exists when we don't need it anymore because of the implementation of oauth 2.

We have to remove the related filed in the User entity if we choose oauth2. (reset_key and and reset_date too).

https://github.com/jhipster/jhipster-quarkus/blob/master/generators/server/templates/quarkus/src/main/java/package/domain/User.java.ejs#L103

<%_ if (authenticationType !== 'oauth2') { _%>
    @Size(max = 20)
    @Column(name = "activation_key", length = 20)
    @JsonbTransient
    public String activationKey;

    @Size(max = 20)
    @Column(name = "reset_key", length = 20)
    @JsonbTransient
    public String resetKey;

    @Column(name = "reset_date")
    public Instant resetDate = null;
<%_ } _%>

**Comment by avdev4j** [comment]
Hi @mraible 
If you have time, could you fix that and rebase your branch?

**Comment by danielpetisme** [comment]
I'll take over, I'll create a new PR with Matt and Joe work and close the open ones.
Ok for you @avdev4j ?

**Comment by danielpetisme** [comment]
Closing PR for #124

**Pull request closed without merging**
