### PR TITLE
Upgrade to Quarkus 3.6.9

### PR DESCRIPTION
**Pull request by mraible**

### CODE REVIEW

**Comment by vishal423** [comment]
Lately, I haven't got much chance to continue quarkus exploration, so, can't say for sure if there is an easy solution. BTW, did you try setting content type in the response to see if that works?

**Comment by mraible** [comment]
All tests pass with Quarkus 3.6.9 so this seems to be related to version 3.7+. Maybe we should just release this version with 3.6 and upgrade to 3.7 later?

**Comment by mraible** [comment]
FWIW, I think we should release with 3.6 now and figure out how to upgrade to 3.7 later.

**Comment by emilpaw** [comment]
I don't see a reason why it would preferable to wait for 3.7 for a release. It's not clear when the issue hindering the update will be resolved.

Another release can be made after the update.

**Comment by DanielFran** [comment]
3.8 is out: https://quarkus.io/blog/quarkus-3-8-released/

**Comment by vishal423** [comment]
I can try to do a release later tonight or tomorrow morning.

**Comment by vishal423** [comment]
> All tests pass with Quarkus 3.6.9 so this seems to be related to version 3.7+. Maybe we should just release a version with 3.6 and upgrade to 3.7 later?

I spent some time on this issue and it stems from the authentication failure while making a GET user request. Strangely, the code works with 3.6.x and that seems wrong to me. 

If you replace the code 
```
        var updatedUser = get("/api/admin/users/{login}", managedUserVM.login).then().extract().body().as(User.class);
``` 
with
```
        var updatedUser = given()
            .auth()
            .preemptive()
            .oauth2(adminToken)
            .accept(APPLICATION_JSON)
            .when()
            .get("/api/admin/users/{login}", managedUserVM.login)
            .then()
            .extract().body().as(User.class);
```
then, the test seems to work fine (change needs to be done across all GET User calls that don't pass the JWT token)
 
I see it as a security bug that seems undetected before 3.7.x release. I will hold release as I believe we must address this.

**Pull request merged**
