### PR TITLE
Enable hibernate second level cache

### PR DESCRIPTION
**Pull request by avdev4j**
related to #9

### CODE REVIEW

**Comment by avdev4j** [comment]
I have simplify the "when" condition in the prompt file to avoid too much complexity when we handle only a part on those conditions. We probably need to update this "when" condition when the blueprint will move forward.

**Comment by nshaw** [comment]
> Also I wonder if we should exclude test files from the Sonar quality gates

I'm in favor of excluding tests from Sonar duplication checks. Requiring low duplication in test classes often leads to tightly coupled/unreadable test code.

**Comment by joewhite101** [comment]
@avdev4j Can you take a look at the sonar failure on this one?

**Comment by avdev4j** [comment]
It comes from the server.spec.ts. I wonder If we should exclude test files from sonar analysis... anyway I know how to fix it.

**Comment by joewhite101** [comment]
LGTM

**Pull request merged**
