### PR TITLE
Update generator-jhipster to 8.8.0

### PR DESCRIPTION
**Pull request by mshima**

### CODE REVIEW

**Comment by mshima** [comment]
> @mshima Latest error is:
> 
> ```
> Error: Template file npmw was not found at /home/runner/work/generator-jhipster-quarkus/generator-jhipster-quarkus/generators/server/templates,/home/runner/work/generator-jhipster-quarkus/generator-jhipster-quarkus/node_modules/generator-jhipster/dist/generators/server/templates,/home/runner/work/generator-jhipster-quarkus/generator-jhipster-quarkus/node_modules/generator-jhipster/dist/generators/java/generators/node/templates,/home/runner/work/generator-jhipster-quarkus/generator-jhipster-quarkus/node_modules/generator-jhipster/dist/generators/spring-boot/templates
> ```

There is a few more issues.

**Comment by mshima** [comment]
no db is broken https://github.com/mshima/generator-jhipster-quarkus/actions/runs/12486366188/job/34846357574

**Comment by mraible** [comment]
OK. I'll add a bug bounty to try and get this fixed.

**Comment by mshima** [comment]
@mraible the nodb sample was disabled.
The samples workflow has a different name and the additional samples workflow enabled it.
I've removed the new samples workflow to match old samples.

I'll remove the bounty since the nodb issue is not a regression.

PR is ready now.

**Review by mraible — APPROVED** [review]

**Pull request merged**
